### ISSUE TITLE
What WAD are you currently working from?

### ISSUE THREAD

**Issue by nikitalita** [viciious/d32xr#103]
Building from source, the game refuses to start when built with the 32x iwad because S_START is missing; I fixed that bug, but now it just hangs on a black screen. There's more indications in the code that you're working from some unknown new WAD; what is this WAD you're working from?

**Comment by viciious** [comment]
Use the IWAD from D32XR ROM.

**Comment by viciious** [comment]
Please also use discussion for general purpose questions

**Comment by mjBrickman** [comment]
I obtained an IWAD from the US version of 32x DOOM through the method specified in an older README.MD file and after compilation, I received the same S_START error on both emulators and real hardware. Is there anything that I'm doing incorrectly?
