### ISSUE TITLE
Demo 1 desync

### ISSUE THREAD

**Issue by viciious** [viciious/d32xr#22]
Similar to https://github.com/team-eternity/calico-doom/issues/1

Except that in our case, the imp behind the door shoots too early (and misses) and the second imp on the floor below isn't triggered at all. When the player opens the second door and shoots the third imp, he misses and proceeds moving forward.

**Comment by Erick194** [comment]
This version of your project uses the original Doom 32x demo sequence? If so, there is a certain part of the calico code that will not work correctly with the demo, I will try to find out what is happening, it is also possible that there is to make some changes in p_sight.c

**Comment by viciious** [comment]
No, I'm actually using the original Jaguar demo since that was easier :)
Let me know if you need the WAD file for debugging - your help'd be much appreciated

**Comment by Erick194** [comment]
Sounds good to me, I need the wad, but I think I have already identified the problem

**Comment by Erick194** [comment]
In the P_MobjThinker function of the commit you made
https://github.com/viciious/d32xr/commit/07dad1d1bf7d3bdde7899f99caba1f7310e60551#diff-ddab3f751a6a747d315c434be6ec3d7818cee881ab0de5baa538918fe6865371L479

it doesn't comply with the modification I made for calico https://github.com/team-eternity/calico-doom/commit/2b4af6042ec214f49466ffd94d029749a7b82888#diff-499a890f720d7677b0d017d544a1e79929638e596e0a02798ba1ac74f40f5fdaR480, that all jaguar-based ports meet those lines in the P_MobjThinker function, that modification is essential for the sync of the demo.

**Comment by viciious** [comment]
> it doesn't comply with the modification I made for calico [team-eternity/calico-doom@2b4af60#diff-499a890f720d7677b0d017d544a1e79929638e596e0a02798ba1ac74f40f5fdaR480](https://github.com/team-eternity/calico-doom/commit/2b4af6042ec214f49466ffd94d029749a7b82888#diff-499a890f720d7677b0d017d544a1e79929638e596e0a02798ba1ac74f40f5fdaR480), that all jaguar-based ports meet those lines in the P_MobjThinker function, that modification is essential for the sync of the demo.
> 
> It doesn't sync if you use the P_SetMobjState (mobj, mobj-> state-> nextstate) function;

Yeah, it actually was making things even worse. Besides, my version is closer to the original port.

**Comment by viciious** [comment]
Note that d32xr is different from calico in that it doesn't use deferred removal of entities, that might also be at play here.

**Comment by Erick194** [comment]
My discord user: Erick194#0791

**Comment by viciious** [comment]
> 
> 
> My discord user: Erick194#791

That didn't help  - there's no global search by user id on discoord. Unless we're hanging out on the same server, it's impossible to start a DM with a person there.

**Comment by viciious** [comment]
Okay, I've decided to drop compatibility with Jaguar Doom demos and record new ones instead. Case closed.
