### ISSUE TITLE
I fixed the dd command for using the prebuild rom

### ISSUE THREAD

**Issue by combo-pizzaroll** [viciious/d32xr#3]
Granted I have no experience with dd. I figured it out by inspecting the rom with a hex editor and figuring out where the iwad header was read from and the file was supposed to end. Block size 32 wouldn't put it in the correct location when using seek.  I'm not sure what count does but it was cutting off the file too early. Removing it put everything in the correct location

dd if=doom32x.wad seek=6093 bs=16 conv=notrunc of=D32XR.bin

*tested in windows 10 using the windows dd port and the cygwin terminal version

@viciious is this mostly correct or is there some difference between linux dd?

**Comment by viciious** [comment]
Yeah, that works fine. I might have pasted the wrong command in my original post but there have been reports of people successfully running the game nonetheless!

**Comment by combo-pizzaroll** [comment]
Ah that's good. I had a lot of fun figuring it out so it's not a problem : ) .  I also noticed the command in the build file looks quite different so maybe they did a full compile of it? I snipped this from build.yml:

   dd if=/dev/zero bs=1K count=2324 of=doom32x.wad && \
          make -f Makefile.mars clean && make -f Makefile.mars debug

**Comment by combo-pizzaroll** [comment]
At any rate this is resolved for me so I'll close it. Good luck with the project btw! I've always been fascinated by the idea of a better port of doom to the 32x
