### ISSUE TITLE
CD Audio not working on Model 1 Sega CD

### ISSUE THREAD

**Issue by chmcarro** [viciious/d32xr#31]
When I switch the audio type to CD, I get no CD audio, just the gun fire. When I exit the pause menu and return and choose CD audio again, the disc drive opens. When an audio CD is inserted, the disc is not read and there is no CD audio.

When I reset the Genesis with the CD inserted, the game runs and the disc access light is blinking red, but no audio is played.

The music CD plays fine within the Sega CD BIOS media player.

If I understand correctly, the intention is to play any music CD with the Sega CD? Or is there a specific disc ISO to burn?

**Comment by chmcarro** [comment]
I'd like to be able to use the Doom Redbook CD audio

https://www.moddb.com/games/doom/addons/doom-redbook-cd-audio-psx-and-3do-music1

Can you tell me what the track order should be?

**Comment by viciious** [comment]
The intro should be the first track, victory track should be the second to last track, the intermission track should be the last track. Everything in between is used for playback on maps in sequential order.

**Comment by chmcarro** [comment]
Thanks again. So if I am following you, this would be the complete CD 27 track listing? (based on 3D0 audio)
https://doomwiki.org/wiki/3DO

Intro E1M7
Map 1 E1M1
Map 2 E1M2
Map 3 E1M3
Map 4 E1M4
Map 5 E1M5
Map 6 E1M6
Map 7 E1M7
Map 8 E1M8
Map 9 E2M1
Map 10 E2M2
Map 11 E2M9
Map 12 E1M1
Map 13 E1M2
Map 14 E1M3
Map 15 E1M4
Map 16 E1M5
Map 17 E1M6
Map 18 E1M7
Map 19 E2M1
Map 20 E3M2
Map 21 E2M9
Map 22 E1M6
Map 23 E1M8
Map 24 E1M9
Victory E1M8
Intermission E1M1

**Comment by viciious** [comment]
Follow instructions over here: https://github.com/viciious/d32xr/blob/master/readme-cdda.txt

**Comment by viciious** [comment]
Also, this is a closed issue, I'm going to stop communicating here from now on.
