### ISSUE TITLE
Unable to save on Everdrive-MD on Genesis Model 1

### ISSUE THREAD

**Issue by chmcarro** [viciious/d32xr#32]
The game save screen displays:

"Reach your first checkpoint after the first area"

Even after completing the first level

**Comment by chmcarro** [comment]
This is now fixed by changing the ROM text from 32X to Genesis. This was also previously completed and how Knuckle's Chaotix was saving:

https://krikzz.com/forum/index.php?topic=5136.0

**Comment by viciious** [comment]
Alright, thanks. I'll change the header to SEGA GENESIS in the future update.

**Comment by viciious** [comment]
> 
> 
> This is now fixed by changing the ROM text from 32X to Genesis. This was also previously completed and how Knuckle's Chaotix was saving:
> 
> https://krikzz.com/forum/index.php?topic=5136.0

Try v1.2a available on romhacks.net
