### ISSUE TITLE
Proper IWAD dumping instructions

### ISSUE THREAD

**Issue by gameblabla** [viciious/d32xr#34]
I can get this to work of sorts but there's just one problem though...

`Dump the IWAD file "doom32x.wad" from your Doom32x cartridge. Dump from address 0xBB000 to the end of the ROM.`

This doesn't fully work because it seems to expect graphics and sound effects from elsewhere that is not found in the IWAD.
So the game will work but it will have lots of missing graphics, sound etc..

![fusion](https://user-images.githubusercontent.com/8717966/140632302-ff7cf730-1b62-4bd1-be9d-e4e11d18ca1e.png)

**Comment by viciious** [comment]
There are incomplete/outdated instructions at doomworld: https://www.doomworld.com/forum/post/2373614

However, there's always going to be stuff that will be missing such as level fixes, that's exclusive to the 32X Resurrection patch and which we can't make available on GitHub.

**Comment by viciious** [comment]
If someone contributes a guideline for making a hybrid IWAD, I'm fine with it, but I don't see myself writing one.

**Comment by gameblabla** [comment]
Thanks to the script, i was able to build a working image. I did have to change the content.json manually for the stock doom32x.wad as it would otherwise try to load maps that didn't exist.
I don't really care much for the 32X Resurrection levels in my case so this will do for me : )

**Comment by chunkyjackson** [comment]
Saxman made a tool back in 2010 that made a proper doom32x.wad file out of the ROM that you could edit and restore back into the 32x version. The tool is here: https://www.romhacking.net/utilities/649/

**Comment by viciious** [comment]
> 
> 
> Saxman made a tool back in 2010 that made a proper doom32x.wad file out of the ROM that you could edit and restore back into the 32x version. The tool is here: https://www.romhacking.net/utilities/649/

That tool messes up a lot of stuff in the WAD, I don't recommend using it.
