### ISSUE TITLE
Crashing on Model 1 Genesis, Model 2 Sega CD with V1 Mega Everdrive

### ISSUE THREAD

**Issue by vitellizzle** [viciious/d32xr#36]
Full disclosure, there is a chance my Everdrive is one of those Chinese clones. I am not sure how to tell. But once I started using the 1.4 patch, the game will freeze at random intervals. The music will keep playing, both FM synth and CD audio, but the screen will be completely frozen - no movement whatsoever. It can be during gameplay, while on the pause menu, after 5 seconds, after 5 minutes, after 10 minutes, etc. There doesn't seem to be any rhyme or reason. I'm not sure which patch I was using before, just that the patch I used in October was fine and it was not doing this until I patched it to version 1.4. But again, it might be the fault of my Everdrive.

**Comment by viciious** [comment]
Not sure how do you expect us to debug this issue without having access to real hardware.

**Comment by lordviceroy** [comment]
I'm using the following setup with no issues:

- NTSC-U CDX
- NTSC-U 32X
- Mega Everdrive X5 OS 3.06 - Official, bought directly from Krikzz

Unfortunately I have no idea which version of Resurrection I am using - is there any way to check the version number in-game?

@vitellizzle, if you're still having this problem, some more details that might be helpful from you are:

- Which Everdrive is it, and what OS version? You can find the OS version in the menu (toolbox->about)
- Can you post a picture of the Everdrive cartridge and the PCB inside?
- Did you patch the ROM yourself, or download it from somewhere?
