### ISSUE TITLE
v1.3-v1.5 : official 6 pad buttons not responding after a few seconds on real hardware

### ISSUE THREAD

**Issue by blinard-BIOINFO** [viciious/d32xr#37]
This happens on real hardware.

Hardware: 

Megadrive 2 - VA1 PAL - with switches 50/60Hz and  ENG/JAP
32X NTSC JAP with region switch
Official 6 buttons controller
Official Mega-Everdrive x7 bought directly from Krikzz

Issue:

When launching the game, pressing buttons on the pad is responsive for 2 to 3 seconds in 60Hz/NTSC.
This extends to 45 seconds in 50Hz/PAL.

Then, the pad does not respond anymore, the game runs, but it is impossible to do anything.
I can manage to enter a 1 player game when i smash rapidly the buttons during these 3 first seconds in 60Hz/NTSC, then nothing, no response. In 50 Hz/PAL, this is true for the 1st minute, then the pad do not respond anymore.

The same rom works perfeclty well when using a 3 buttons control pad from the start.
When removing the 6 buttons pads of a running game and after the issue happens, and after inserting a 3 buttons pad, there is still no response, it seems the game logic does not process inputs anymore.

The same 6 buttons pad works perfectly well with other megadrive / 32X games (original doom 32X, virtua racing 32X ...)

**Comment by blinard-BIOINFO** [comment]
With the same rom, there is no issue when using an official 3 buttons control pad.

**Comment by blinard-BIOINFO** [comment]
Complementary observations :

- When switching everything to 50 Hz (megadrive 2 + 32x) , things get worse, the pad works for 1 second, i can only pass the start screen with fire animation.
-  When using a retrobit unofficial 6 buttons pad in 60 Hz mode, it works ! no issues anymore ! 
- When using the same retrobit unofficial 6 buttons pad in 50 Hz mode, it does not work, like the official pad.
- I don't think the issue comes from my official 6 buttons pad, it works well with many other games, including 32X games.
- Interestingly, when using the rom "
- controller test joyzz 6-button from Krikzz, I can see that the official pad responds with expected bits, while the retrobit pad does show a different pattern (which the rom did not expect, as it show something different than the buttons I press during the test).

All this makes me think there may be something related to a frequency issue ?

**Comment by blinard-BIOINFO** [comment]
Other note: with patch v1.3, the issue happens after around 1 or minutes of gameplay, so it's there, but for some reason not so immediate.

**Comment by ChillyWillyGuru** [comment]
Does the 6-button pad work with Wolf32X?

Also, D32XR does not handle hot-plugging controllers. Do not switch controllers while the game runs.

**Comment by blinard-BIOINFO** [comment]
@ChillyWillyGuru 
I confirm that I see the exact same pattern with Wolf32X : official pad = no response, retrobit pad = functionnal in 60Hx mode.
I also tested RIck Dangerous (version b5) by curiosity, and both pads works fine.

**Comment by lordviceroy** [comment]
I'm using the following setup with no issues:

- NTSC-U CDX
- NTSC-U 32X
- Official 6 button pad
- Mega Everdrive X5

Unfortunately I have no idea which version of Resurrection I am using - is there any way to check the version number in-game?

If I had to speculate, I'd try disabling the in-game menu on the Everdrive and see if that resolves the problem. It is known to cause issues with some games. If that still doesn't resolve the problem, it could be related to the 50/60Hz mod or the region mod on the 32X. For the 32X region mod, try leaving it in JP mode to see what happens (I don't think the Everdrive cares what region your console is and neither does Doom).

**Comment by viciious** [comment]
Please try again now that v2.0 is out

**Comment by blinard-BIOINFO** [comment]
@viciious 
I confirm that v2.0 resolved this issue.
I played 15 minutes with the same hardware without any issue.

**Comment by viciious** [comment]
Thanks!
