### ISSUE TITLE
Md Vdp, clear vsram typo

### ISSUE THREAD

**Issue by fedex81** [viciious/d32xr#39]
Hello,
I believe the following line:
https://github.com/viciious/d32xr/blob/ac9dd79a8dd9410157956bfbb1c22c4e573b6f66/src-md/crt0.s#L131

Should be changed to:
` move.l  #0x40000010,(a0)         /* write VSRAM address 0 */`

**Comment by ChillyWillyGuru** [comment]
Yep, that's a whoopsi, all right! Good catch. It hasn't affected anything yet because that's the routine that clears the VDP scroll ram, which we don't use. If we tried using a MD side scrolling layer, it might have shown some weird issue if we assumed the table started cleared to 0.
