### ISSUE TITLE
[Low Priority] Display version number on credits screen in-game

### ISSUE THREAD

**Issue by lordviceroy** [viciious/d32xr#41]
I realized today when I was looking at some of the open issues to try and repro them that I don't have a copy of the files I used to build the ROM anymore, and I have no idea which version I am using... it may be helpful to have a reference to the version number in the game's credits screen during the attract sequence. This is, of course, not at all an important change, so feel free to close as a "no fix" if you're meh about it.

Thanks for all of your efforts on this project!

**Comment by viciious** [comment]
The version is now displayed in the second credits screen. You can also view the ROM header to determine the version of the game.
