### ISSUE TITLE
Doomguy's Faces never reacts when hurt by Hazard Zones

### ISSUE THREAD

**Issue by TheDuke72** [viciious/d32xr#48]
No idea if this was addressed yet, But when Doomguy is in the Hazard zone, Lava, Toxic Waste, etc. His faces don't change to an Frontal Anger\pain Face, In fact the Frontal Anger\pain face doesn't happen when enemies attack you from the front. Also when you pick up the Invulnerability Sphere, His eyes never changed into golden white.

**Comment by TheDuke72** [comment]
Doomguy has a pain sprite, but its only used when your holding the fire button for about 2 -3 seconds and he's making that pain state, otherwise left or right pain states do work when damaged. Idk if you have a god mode cheat in D32xR, I may thought I had remembered I used the cheat for God Mode and His God Face Sprite was there. I found this image you posted in the Doomworld Site, Though idk if that's still there. https://www.doomworld.com/forum/topic/119202-doom-32x-resurrection/?page=3

**Comment by TheDuke72** [comment]
![IMG_20220412_101659172_HDR](https://user-images.githubusercontent.com/85081815/162984118-6de662ad-8d9d-42d6-a3f2-f77d4dbf1e4d.jpg)
Face Pain Sprite animation while firing the gun. They're just minor nit pickings. But I thought that It could help improve on the port.

**Comment by viciious** [comment]
https://github.com/viciious/d32xr/commit/7e69d9e92ca05bdd950982839449e50bdd4914d3

**Comment by fonic** [comment]
> There's also only 1 face animation for the pain state, which is only applied if player takes 30 damage or more.

That should be the famous 'ouch' face, right? The one that was hardly seen in the original DOS version due to a bug.

> Doomguy has a pain sprite, but its only used when your holding the fire button for about 2 -3 seconds and he's making that pain state, otherwise left or right pain states do work when damaged.

The sprite that appears when holding down the fire button should be the same as the 'frontal hit' face, so it could be used for frontal hits, too (*). I think that would be a great addition, since doomguy's face is an indicator for the location of attackers. Personally, I find it rather distracting to have doomguy look left/right when being attacked from the front. Probably due to the fact that I grew up with the DOS version.

(*) Judging by this sprite sheet:
https://www.reddit.com/r/Doom/comments/8pllaa/doomguy_face_spritesheet/

**Comment by TheDuke72** [comment]
> The sprite that appears when holding down the fire button should be the same as the 'frontal hit' face, so it could be used for frontal hits, too (*). I think that would be a great addition, since doomguy's face is an indicator for the location of attackers. Personally, I find it rather distracting to have doomguy look left/right when being attacked from the front. Probably due to the fact that I grew up with the DOS version.

Thats what I was trying to get at here, You explained it better than me.

**Comment by fonic** [comment]
> Thats what I was trying to get at here, You explained it better than me.

Thanks :) It was indeed a bit unclear from the other comments.

> Doomguy has a pain sprite, but its only used when your holding the fire button for about 2 -3 seconds

Just as a side note: I just tested this and the face only appears when using the _chaingun_ or the _plasma gun_. It won't appear for any other weapon. Curious, I don't remember it that way from the original, but I'd have to verify to be sure. Actually, I kind of like it this way, but maybe it should also be displayed for the chainsaw (as that is also a weapon where you'd typically hold down fire to mow down enemies).

**Comment by viciious** [comment]
Better? https://github.com/viciious/d32xr/commit/0259a0af09782c0539184e29e41e191643eaa098

**Comment by TheDuke72** [comment]
No, That's an ouch face, and it's supposed to do 30 damage. I was referring to "frontal hit" Face which was only used when holding down the fire button with a chain gun on this port. and Its supposed to be used when taking damage and Non directional Hazard Damage. Do you think it's possible to implement that?
![Doom Resurrection000](https://user-images.githubusercontent.com/85081815/174506364-b1e0a740-0a10-4271-a17e-905d87492652.png)
?

**Comment by viciious** [comment]
> when taking 30 damage or more
20 in vanilla Doom

JagDoom had it at 30, which is what prevented the ouch face from being displayed when taking damage from env hazards

**Comment by TheDuke72** [comment]
> > when taking 30 damage or more
> 
> 20 in vanilla Doom
> 
> JagDoom had it at 30, which is what prevented the ouch face from being displayed when taking damage from env hazards

Ah Thats why, I over looked that, sorry. But in Dos, Pain Face was displayed instead of Ouch Face.

> > On DOS, That Face is also used when using a chainsaw
> 
> As is in JagDoom and D32XR

The Pain Face doesn't display with a chainsaw on D32XR, I've already tested that.

**Comment by viciious** [comment]
https://github.com/viciious/d32xr/commit/8fc557a43fd7b7adcb131b336be66aca14d7cb33

**Comment by viciious** [comment]
I consider the original issue to be fixed.
