### ISSUE TITLE
Strobing lights glitch.

### ISSUE THREAD

**Issue by TheDuke72** [viciious/d32xr#49]
So after trying out the 2.0 patch. The strobing lights now just instantly goes bright after the lights dim to pitch black instead of fading in and out like they're supposed to.

**Comment by viciious** [comment]
I'd appreciate if you could tell which spot on which map I'm supposed to look into.

**Comment by TheDuke72** [comment]
My apologies, E1M2. The area where you shoot or punch the secret door to open.

**Comment by viciious** [comment]
Fixed in f638fbe77fa0b0c25bf3cf65adb926f0ad179d31
Thanks!
