### ISSUE TITLE
Spectre stuck in exit room of area 6

### ISSUE THREAD

**Issue by fonic** [viciious/d32xr#53]
In the exit room of area 6, right below the 'EXIT' sign, a spectre seems to be stuck inside the wall.

Playing version 2.0, created using the patch from [Romhacking.net](https://www.romhacking.net/hacks/6269/) and the original 'Doom (Europe) 32X' rom, with difficulty UV, on AYN Odin with RetroArch Plus, core PicoDrive.

Great project, by the way!

**Comment by 32XFan** [comment]
This bug is already present in the original Doom for the 32X

https://youtu.be/08lnwLHFc5Y
