### ISSUE TITLE
Radiation suit without purpose in area 13

### ISSUE THREAD

**Issue by fonic** [viciious/d32xr#54]
In area 13, there is a hidden/secret radiation suit (see screenshots below). However, there is no actual use for it anywhere within the map afaict.

There are two hazardous areas in the map:
- a small area in front of a demon portrait (nothing to do there and trivial to avoid)
- an 'outdoor' area with toxic green waste (but nothing to discover/gain there either)

Thus, I wonder if the placement of that radiation suit was a mistake - was it maybe supposed to be a different item, e.g. a soulsphere would make much more sense?

![Screenshot_20220527-1](https://user-images.githubusercontent.com/14027079/170693647-22054a61-b02b-4370-824f-36dfafee1f1c.png)
![Screenshot_20220527-2](https://user-images.githubusercontent.com/14027079/170693650-bb146f3c-5eb6-4427-8ce4-abc7faf221fc.png)

**Comment by viciious** [comment]
It's a leftover.. The hazardous areas in the original map got removed when the game was being ported to Jaguar/32X

**Comment by viciious** [comment]
> > It's a leftover.. The hazardous areas in the original map got removed when the game was being ported to Jaguar/32X
> 
> Interesting. Makes sense. Is that a well-known fact or how do you know? Probably from comparing the map to the original?
> 
> It could still be changed to something more useful though.

https://doomwiki.org/wiki/MAP13:_Command_Center_(Console_Doom)

See the Bugs section
