### ISSUE TITLE
Version 2.0 and MegaCD2 OST

### ISSUE THREAD

**Issue by Indibilio** [viciious/d32xr#57]
Hello! Thanks for the Doom Resurrection 32x!!!

I am playing the game on real hardware. Until today I have played version 1.5 together with the real MegaCD2, and on it, the CR-R with the OST.

Today I have made the version 2.0 cartridge and this version does not recognize the OST from MegaCD2, I press Start, I go to Audio options and I only have OFF or FM. Then I put the version 1.5 cartridge back in and the OST sound from MegaCD works.

It has been excluded in version 2.0 to play OST from real hardware, and it only works with MegaSD?

Thank you!

**Comment by viciious** [comment]
v2.0 has broken SegaCD audio support, so you gonna have to wait until v2.1 to be able to use real CDs for music, I'm afraid

**Comment by viciious** [comment]
Fixed in v2.1

**Comment by Indibilio** [comment]
thanks!!!
