### ISSUE TITLE
Weapons off center after patch

### ISSUE THREAD

**Issue by TheDuke72** [viciious/d32xr#64]
So the patch notes says "Fixed weapon position being off-center at some screen resolutions." When I played the v2.2b, pretty much every weapon now is off center except maybe the pistol, No matter what screen resolution. Tested on Kega Fusion and Hardware.
For example, Plasma shots looked off when fired from the rifle, even the BFG plasma ball looked off when firing. at first it looked like the projectiles were off, but it turns out it was the weapon sprites themselves. also you can tell the sprites aren't in line with the doomguy face sprite. I also drew a red line in the center of the screen to show you how off centered the plasma rifle is. If you need more screenshots, I'll be glad to upload more.
![Doom Resurrection000](https://user-images.githubusercontent.com/85081815/194786373-17bd245c-80fb-47ea-ab9f-765544f46320.png)
![Doom Resurrection001](https://user-images.githubusercontent.com/85081815/194786374-42a6311f-f14e-4e82-9070-1ea49aa85857.png)
![Doom Resurrection0red](https://user-images.githubusercontent.com/85081815/194786375-081712e9-87b6-4bb5-8c9a-103273a0fd40.png)

**Comment by TheDuke72** [comment]
My game isn't set to widescreen, perhaps the bug might be affecting the screens with 4 : 3 ratio?

**Comment by viciious** [comment]
> > The bug only affects the anamorphic "widescreen" mode is already fixed in master: [7336443](https://github.com/viciious/d32xr/commit/73364439b29640c18829baf88c3fa5cb81cbd4f6)
> 
> My game isn't set to widescreen, and when I do set it to widescreen, same thing happens. I only play retro games on CRT or on 4:3 aspect. perhaps the bug might be affecting the screens with 4 : 3 ratio?
> 
> Note, I don't have a proper way of playing my games on a 16:9 ratio to test this.

Well, in that case, the screenshots you've posted match the OG:

<img width="536" alt="изображение" src="https://user-images.githubusercontent.com/1173058/194939360-317ffa84-f68e-4866-99df-ceb2ce5c380f.png">

**Comment by TheDuke72** [comment]
Coming back again, So after you posted that screenshot, I checked again. even the newer doom ports have this issue. , just less apparent, I thought the weapons were off center because of the projectile shots where off from when firing your weapon. but it appears that is a vanilla bug. The projectiles only line up with the weapon sprite when they lock on to enemies and barrels.

After playing DOOM for so long, to think I'd never notice this bug till now. How unprecedent of me.  Probably more apparent on the Jag doom? idk. will close this issue now, sorry to bother.
