### ISSUE TITLE
Sound Engine Complete Pile-Up on "Refinery"

### ISSUE THREAD

**Issue by vvVoDkAvv** [viciious/d32xr#71]
After a certain amount of time, around five minutes by my estimate, the game slows to slide-show speeds, and the sound engine is reduced to a garbled mess of sounds and music playing one tone at a time.

The sound engine was set to "Auto" in both cases where this occurred.

After either switching sound engines manually or switching the music to off then back on to FM, the game plays normally but with the absence of music. In one of these two cases, the game's logic was greatly affected and all monsters, projectiles, and attacks were operating at around 250% their regular speed and pacing. This remained until the level was completed, with the subsequent levels playing like normal without these issues, at least for the next few levels to where I am now.

The hardware this occurred on is as follows:
Problem encounterted on this hardware:
Mega Everdrive x3, Lexar 2GB Micro SD card
Model 1 Sega Genesis, Signetics processor
Model 1 Sega CD
Launch Sega 32x

**Comment by viciious** [comment]
Please see the comment in https://github.com/viciious/d32xr/issues/70#issuecomment-1689615357

**Comment by viciious** [comment]
Please try v3.1

**Comment by Mittens0407** [comment]
> The hardware this occurred on is as follows: Problem encounterted on this hardware: Mega Everdrive x3, Lexar 2GB Micro SD card Model 1 Sega Genesis, Signetics processor Model 1 Sega CD Launch Sega 32x

@vvVoDkAvv Hello, this doesn't have anything to do with the bug you've reported, but I can't find another way to contact you on this site. Would you mind sending a photo of your Mega Everdrive x3's system information window? It looks like this:

![IMG_20230908_212250579small](https://github.com/viciious/d32xr/assets/94572904/88e1f3b7-3d43-444f-80d9-d28a6aab9e22)

I've been troubleshooting my x3 and its issues with bank switching, and it would be helpful to see what firmware you're using among other things. If you can send a photo, thanks in advance.
