### ISSUE TITLE
"R_FlatNumForName: not found" error

### ISSUE THREAD

**Issue by Retro-VuCCy** [viciious/d32xr#72]
I get the error in subject, right after credit screen, at the beginning of the game. Patch used is 3.1 and I have used deltapatcher for Windows.
![20230825_144419](https://github.com/viciious/d32xr/assets/143192591/ba7e4619-9f24-4d88-8366-1ee5a8409df6)
My set in picture attached below
![20230825_150832](https://github.com/viciious/d32xr/assets/143192591/69dc300c-5004-4e07-a719-d8f2be8ef695)

**Comment by viciious** [comment]
It's hard to tell from the picture which flashcart model you're using

**Comment by Retro-VuCCy** [comment]
Megadrive V3 (chinese clone). Previous version (2.2) was working without problems. Thanks for super quick answer!
![20230825_151218](https://github.com/viciious/d32xr/assets/143192591/d99cbf2a-21d9-43e2-aa6a-6bad21dae7a4)

**Comment by viciious** [comment]
Chinese everdrive knockoffs aren't going to work with v3.0

**Comment by Retro-VuCCy** [comment]
😞 that is a real pitty. I hope it will be solved in a near future!
