### ISSUE TITLE
Z_Malloc: failed on 24 (version 3.1)

### ISSUE THREAD

**Issue by ferraca** [viciious/d32xr#73]
I am receiving this error when I access the version 3.1: "Z_Malloc: failed on 24" with black screen. I am using the real Hardware (32x + Genesis 2 + Sega CD Model 2 + Everdrive X5). Version 2.2b works fine.

**Comment by viciious** [comment]
It's an Everdrive problem: https://krikzz.com/forum/index.php?topic=12641.0
