### ISSUE TITLE
SegaCD 32x version?

### ISSUE THREAD

**Issue by Indibilio** [viciious/d32xr#75]
Hello, because this version 3.1 exceeds the 4MB ROM size, and makes it difficult to make a cartridge to play, for example, using the SONICCD123 PCB, it would be possible for this version 3.1 to be "converted" to a SegaCD_32x format and use the save game function into the SegaCD memory? without using cartridge.

Thanks for your work!!

**Comment by viciious** [comment]
CD32X doesn't have enough RAM to run Doom

**Comment by Indibilio** [comment]
Thanks.
