### ISSUE TITLE
Normal doors play fast door sound when reopening due to being blocked

### ISSUE THREAD

**Issue by fonic** [viciious/d32xr#78]
Playing version 3.1.

https://github.com/viciious/d32xr/assets/14027079/ae512d29-dae9-4270-b1c8-3f45e7fab823

**Comment by fonic** [comment]
Judging from the code, it could be that

https://github.com/viciious/d32xr/blob/901869a1c72ccbaf1ed596ccd4a69676d697229a/p_doors.c#L79-L91

Needs to be

```
switch (door->type)
{
	case blazeClose:
	case close:		/* DO NOT GO BACK UP! */
		break;
	case blazeRaise:
		door->direction = 1;
		break;
	case blazeOpen:
		door->direction = 1;
		S_StartPositionedSound((void *)door->sector,sfx_bdopn,&P_SectorOrg);
		break;
	default:
		door->direction = 1;
		S_StartPositionedSound((void *)door->sector,sfx_doropn,&P_SectorOrg);
		break;
}
```

Just a guess, however, I have no development environment set up to test this hypothesis.

**Comment by viciious** [comment]
Thanks! Fixed in 3d1822b5b2bf01aad9b2214c7073f4e4b45e1090

**Comment by fonic** [comment]
> Thanks! Fixed in [3d1822b](https://github.com/viciious/d32xr/commit/3d1822b5b2bf01aad9b2214c7073f4e4b45e1090)

Are you sure that this is the correct fix, though? I might be wrong, but I assume fast doors will now emit the normal door sound when reopening due to being blocked, no? That's why a added a case for `blazeOpen` in my original post.

**Comment by viciious** [comment]
Hm.. You're right. I was originally confused by ho chocolate Doom and OG handle the crushed case for fast doors: 
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/doom/p_doors.c#L141

They seem to skip the blazeOpen case altogether and just play normal door sounds

**Comment by viciious** [comment]
https://github.com/viciious/d32xr/commit/7eddddc95693381c3342052ae8cfe56248a4ab35
