### ISSUE TITLE
Memory mapper

### ISSUE THREAD

**Issue by Developer2704** [viciious/d32xr#85]
With the release of Resurrection 3.1, Doom has gotten so big that it cannot run on flashcarts without a memory mapper. On cartridges like an Everdrive x3 or x5 it just boots to errors. Is it possible to include a mapper inside the rom or make a modification to the everdrive OS to add a mapper?

**Comment by viciious** [comment]
The mapper cannot be added to the ROM. On the ED x5 or x7 try changing the file extension from .32x to .md

**Comment by Developer2704** [comment]
as a .md it cannot save

**Comment by viciious** [comment]
That's an Everdrive issue, there's nothing we can do about it

**Comment by Developer2704** [comment]
i am testing on am emulator and it saves

**Comment by Developer2704** [comment]
crashes on reset and cannot save so i will just run on emulator or get everdrive pro.
