### ISSUE TITLE
Fix Save System for X5 and X7 Everdrive Cartridge

### ISSUE THREAD

**Issue by ferraca** [viciious/d32xr#88]
According to Krikzz the issue about loading Doom Reduction v3.1 is fixed but the game cannot save due to the type of save system:

"I just checked it again and yes, game use 8bit ram, but even byte instead of odd. If via firmware i block writes to even bytes, then saves stop work, but if i block odd bytes it still working fine.
I suppose that all problems simply due the typo in asm code. rd_msd_sram and standard mapper uses this instruction  "1(a0,d0.l),d1 , But for everdrive rd_med_sram by some resaosns used this:  "move.b  0(a0,d0.l),d1"

edit
Game indeed uses 16bit ram. While it can let you save if only even bytes enabled, but loading of such saves results crashes anyway.
Memory bump cleary shows it use bot od and even bytes."

https://krikzz.com/forum/index.php?topic=12641.0

So, please, is it possible to fix the game in order to make the save system working for X5 and X7 Everdrive Cartridge?

Thank you!

**Comment by Arnold101knight** [comment]
up!!!!!!!!!!!

**Comment by viciious** [comment]
Fixed
