### ISSUE TITLE
Can't compile on macos m1 laptop

### ISSUE THREAD

**Issue by asturur** [viciious/d32xr#89]
I was trying to compile the project, to see if i could run it following the dev docker container instructions.
While trying to run make i hit the following issue:

```
make -C src-md
make[1]: Entering directory '/workspaces/d32xr/src-md'
/opt/toolchains/sega/m68k-elf/bin/m68k-elf-as -m68000 --register-prefix-optional -I -I/opt/toolchains/sega/m68k-elf/include -I/opt/toolchains/sega/m68k-elf/m68k-elf/include -I../liblzss crt0.s -o crt0.o
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
 make[1]: *** [Makefile:67: crt0.o] Trace/breakpoint trap
make[1]: Leaving directory '/workspaces/d32xr/src-md'
make: *** [Makefile:116: m68k.bin] Error 2
```

By chance did you hit this ever and know how to work around with it?

**Comment by viciious** [comment]
No, I have never encountered this error. I don't think it has anything to do with the project anyway.

**Comment by asturur** [comment]
I think i ll clarify, I asked because the description of the project does mention compilation and education/learning so i thought building / compiling was part of the project

```
The goal of the project is to have a code base from which a playable version of DOOM for the Sega 32X platform could be compiled. It is primarily focused on preservation and education 
```

i tried to ask since the instructions in the settings file do mention apple silicon, so i thought it was possible in some way and maybe it is but i m not able to do so.

Thank you for your effort and the project, i understand you can't provide support.
Regards.
