### ISSUE TITLE
WAD changes necessary to run 'experiment' branch

### ISSUE THREAD

**Issue by SSNTails** [viciious/d32xr#92]
I'd love to give the latest commits a try. What changes do I need to make to the IWAD that I merge into the build process? Anything other than converting the levels to PC format?

**Comment by viciious** [comment]
Sorry, I'm not providing support for the experimental stuff. It's made solely for my own amusement, you're entirely on your own here

**Comment by SSNTails** [comment]
No worries, thanks for all of your really cool work!
