### ISSUE TITLE
VGM max file size?

### ISSUE THREAD

**Issue by SSNTails** [viciious/d32xr#95]
What's the maximum file size that VGMs can be? (and is that while LZSS compressed, or uncompressed?)

I know the SegaCD cache size is 128kb, but are pieces of the VGM just buffered if it exceeds that?

**Comment by viciious** [comment]
For ZGMs stored in ROM, there's no inherent file size limitation. On the other hand, ZGMs stored in the WORD RAM have a size limit of about 100KBi.
