### ISSUE TITLE
Jag doom out of bounds enemy

### ISSUE THREAD

**Issue by Developer2704** [viciious/d32xr#98]
In map02 there is an out-of-bounds imp preventing you from getting 100% kills. It is just an issue with jag doom level design.

**Comment by viciious** [comment]
Where is it located?

**Comment by Developer2704** [comment]
Above the end level switch

**Comment by viciious** [comment]
I can't see it neither in the game, nor in the editor

![image](https://github.com/viciious/d32xr/assets/1173058/6bc8e827-89f6-4ce8-829a-9bf00fcc5eac)
